default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [style.css,style_.css,style_ie.css,style_ie6.css, ui-lightness/jquery-ui-1.8.custom.css]

  javascripts:    [jquery-1.4.2.min.js, jquery-ui-1.8.custom.min.js, datepicker.js]

  has_layout:     on
  layout:         layout
