<?php
// auto-generated by sfDatabaseConfigHandler
<<<<<<< .mine
// date: 2010/05/29 02:42:01
=======
// date: 2010/05/29 08:10:50
>>>>>>> .r224

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'mysql:host=localhost;dbname=aulavirtual',
  'username' => 'root',
  'password' => NULL,
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
