<?php


/**
 * This class adds structure of 'evaluacion' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
<<<<<<< .mine
 * 06/06/10 00:25:29
=======
 * 06/06/10 00:02:20
>>>>>>> .r240
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class EvaluacionMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.EvaluacionMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(EvaluacionPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(EvaluacionPeer::TABLE_NAME);
		$tMap->setPhpName('Evaluacion');
		$tMap->setClassname('Evaluacion');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('IDEVALUACION', 'Idevaluacion', 'INTEGER', true, 11);

		$tMap->addColumn('NOMBRE', 'Nombre', 'VARCHAR', true, 45);

		$tMap->addColumn('PORCENTAJE', 'Porcentaje', 'INTEGER', true, 11);

		$tMap->addColumn('TIPO', 'Tipo', 'VARCHAR', true, 45);

		$tMap->addColumn('FECHA_FIN', 'FechaFin', 'DATE', false, null);

		$tMap->addColumn('DESCRIPCION', 'Descripcion', 'VARCHAR', false, 100);

		$tMap->addColumn('ESTADO', 'Estado', 'VARCHAR', false, 45);

		$tMap->addColumn('DURACION', 'Duracion', 'INTEGER', false, 11);

		$tMap->addColumn('IDLAPSO', 'Idlapso', 'INTEGER', true, 11);

	} // doBuild()

} // EvaluacionMapBuilder
