<?php


/**
 * This class adds structure of 'res_dada' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
<<<<<<< .mine
 * 05/25/10 15:00:19
=======
 * 05/25/10 19:51:09
>>>>>>> .r209
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ResDadaMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ResDadaMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(ResDadaPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(ResDadaPeer::TABLE_NAME);
		$tMap->setPhpName('ResDada');
		$tMap->setClassname('ResDada');

		$tMap->setUseIdGenerator(false);

		$tMap->addPrimaryKey('NUM_PREGUNTA', 'NumPregunta', 'INTEGER', true, 11);

		$tMap->addColumn('RESPUESTA', 'Respuesta', 'INTEGER', true, 11);

		$tMap->addPrimaryKey('IDNOTA', 'Idnota', 'INTEGER', true, 11);

		$tMap->addPrimaryKey('IDPERSONA', 'Idpersona', 'INTEGER', true, 11);

		$tMap->addPrimaryKey('IDEVALUACION', 'Idevaluacion', 'INTEGER', true, 11);

	} // doBuild()

} // ResDadaMapBuilder
