dev:
  propel:
    param:
      classname: DebugPDO
test:
  propel:
    class: sfPropelDatabase
    param:
      classname: DebugPDO
      dsn: 'mysql:host=localhost;dbname=aulavirtual_test'
      username: root
      password: null
all:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'mysql:host=localhost;dbname=aulavirtual'
      username: root
      password: null
      encoding: utf8
      persistent: true
      pooling: true
