propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  comentarios:
    _attributes: { phpName: Comentarios }
    idcomentarios: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    comentario: { type: VARCHAR, size: '3000', required: true }
    created_at: { type: DATE, required: true }
    updated_at: { type: DATE, required: false }
    idpersona: { type: INTEGER, size: '11', required: true }
    idtema: { type: INTEGER, size: '11', required: true }
    _indexes: { fk_comentarios_persona: [idpersona], fk_comentarios_tema: [idtema] }
  contenido_examen:
    _attributes: { phpName: ContenidoExamen }
    idpregunta: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    pregunta: { type: VARCHAR, size: '100', required: true }
    idevaluacion: { type: INTEGER, size: '11', primaryKey: true, required: true }
    _indexes: { fk_contenido_examen_evaluacion: [idevaluacion] }
  documento:
    _attributes: { phpName: Documento }
    created_at: { type: DATE, primaryKey: true, required: true }
    updated_at: { type: DATE, required: false }
    iddocumento: { type: INTEGER, size: '11', required: true }
    nombre: { type: VARCHAR, size: '45', required: true }
    idpersona: { type: INTEGER, size: '11', required: true }
    _indexes: { fk_documento_persona: [idpersona] }
  evaluacion:
    _attributes: { phpName: Evaluacion }
    idevaluacion: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    nombre: { type: VARCHAR, size: '45', required: true }
    porcentaje: { type: INTEGER, size: '11', required: true }
    tipo: { type: VARCHAR, size: '45', required: true }
    fecha_fin: { type: DATE, required: false }
    descripcion: { type: VARCHAR, size: '100', required: false }
    estado: { type: VARCHAR, size: '45', required: false }
    duracion: { type: INTEGER, size: '11', required: false }
  lapso:
    _attributes: { phpName: Lapso }
    idlapso: { type: INTEGER, size: '11', primaryKey: true, required: true }
  nota:
    _attributes: { phpName: Nota }
    idnota: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    created_at: { type: DATE, required: true }
    updated_at: { type: DATE, required: false }
    nota: { type: INTEGER, size: '11', required: false }
    idpersona: { type: INTEGER, size: '11', primaryKey: true, required: true }
    idevaluacion: { type: INTEGER, size: '11', primaryKey: true, required: true }
    idlapso: { type: INTEGER, size: '11', required: true }
    _indexes: { fk_nota_evaluacion: [idevaluacion], fk_nota_persona: [idpersona], fk_nota_lapso: [idlapso] }
  persona:
    _attributes: { phpName: Persona }
    idpersona: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    nombre: { type: VARCHAR, size: '45', required: true }
    apellido: { type: VARCHAR, size: '45', required: true }
    tipo: { type: VARCHAR, size: '45', required: true }
    cuenta: { type: VARCHAR, size: '45', required: true }
    clave: { type: VARCHAR, size: '45', required: true }
    seccion: { type: VARCHAR, size: '2', required: false }
    estado: { type: VARCHAR, size: '45', required: true, defaultValue: Activo }
    correo: { type: VARCHAR, size: '80', required: false }
    segundonombre: { type: VARCHAR, size: '45', required: true }
    segundoapellido: { type: VARCHAR, size: '45', required: true }
  res_dada:
    _attributes: { phpName: ResDada }
    num_pregunta: { type: INTEGER, size: '11', primaryKey: true, required: true }
    respuesta: { type: INTEGER, size: '11', required: true }
    idnota: { type: INTEGER, size: '11', primaryKey: true, required: true }
    idpersona: { type: INTEGER, size: '11', primaryKey: true, required: true }
    idevaluacion: { type: INTEGER, size: '11', primaryKey: true, required: true }
    _indexes: { fk_res_dada_nota: [idnota, idpersona, idevaluacion] }
  respuesta:
    _attributes: { phpName: Respuesta }
    idrespuesta: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    respuesta: { type: VARCHAR, size: '100', required: true }
    tipo: { type: VARCHAR, size: '45', required: true }
    idpregunta: { type: INTEGER, size: '11', primaryKey: true, required: true }
    _indexes: { fk_respuesta_contenido_examen: [idpregunta] }
  tema:
    _attributes: { phpName: Tema }
    idtema: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    nombre: { type: VARCHAR, size: '45', required: true }
    created_at: { type: DATE, required: true }
    updated_at: { type: DATE, required: false }
    descripcion: { type: VARCHAR, size: '100', required: false }
    idpersona: { type: INTEGER, size: '11', required: true }
    _indexes: { fk_tema_persona: [idpersona] }
