<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/05/20 20:22:45

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'mysql:host=localhost;dbname=aulavirtual',
  'username' => 'root',
  'password' => '1234',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
