<?php
// auto-generated by sfDatabaseConfigHandler
<<<<<<< .mine
// date: 2010/05/26 20:00:40
=======
<<<<<<< .mine
// date: 2010/05/27 03:09:10
=======
// date: 2010/05/26 20:36:59
>>>>>>> .r217
>>>>>>> .r220

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'mysql:host=localhost;dbname=aulavirtual',
  'username' => 'root',
  'password' => NULL,
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
