<?php
// auto-generated by sfDatabaseConfigHandler
<<<<<<< .mine
// date: 2010/06/06 01:01:31
=======
// date: 2010/06/07 22:00:47
>>>>>>> .r248

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'mysql:host=localhost;dbname=aulavirtual',
  'username' => 'root',
  'password' => NULL,
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
