<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/06/07 23:05:37
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
